### ISSUE TITLE
Metadata is different 😵

### ISSUE THREAD

**Issue by kravchenko-anton** [Jemeni11/Ebook-Reader#1]
Hi, I'm running into a problem with epab.  Each epub is unique and written in its own way.  how can i get all the data from all epubs, for example i want to understand how using domparser i can always get the title of the book cover image, also the genres are always in different tags, also with the date (always different formats). are there any solutions (  I can't find anything on the internet about this topic.  thank you very much for helping me, I don't know what I would do without you

**Comment by Jemeni11** [comment]
This is a problem I'm also running into. I do not know how to do this yet.
