### ISSUE TITLE
How I can do narrator?

### ISSUE THREAD

**Issue by kravchenko-anton** [Jemeni11/Ebook-Reader#2]
Hey, how can I dub the book, for example, the person opened the book and does not want to read and wants the narrator to dictate all, can you do this, and how?
Thanks If you search time for help me🥰

**Comment by Jemeni11** [comment]
Hey Anton
What you need is a **Text-To-Speech** library
Here's one for react native: [React-Native-tts](https://www.npmjs.com/package/react-native-tts)
I've never used this before though
[LNReader](https://github.com/LNReader/lnreader) uses this package. 
[Duofolio](https://github.com/farshed/duofolio) also uses this package.
These projects are ebook readers so they should help.
You can use those two projects and the docs to use `react-native-tts` in your project.
Hope this helps!
EDIT: Please note, it looks like this library does not work with Expo
EDIT2: Expo has its own Text to Speech library called [Expo Speech](https://docs.expo.dev/versions/latest/sdk/speech/)
